import { it } from 'vitest';
import * as THREE from 'three/webgpu';
import def from '../src/objects/bldc-inrunner/index';
import { resolveObject } from '../src/objects/resolve';
import { SimpleGeometryCache, createBuildContext, normalizeBuild, registerObjectMaterials } from '../src/objects/buildSupport';
import { createFakeServices } from './helpers/fakeServices';
it('probe', () => {
  const services = createFakeServices();
  registerObjectMaterials(def as never, services.materials);
  const r = resolveObject(def as never, {});
  const part = r.parts.find((p) => p.id === 'can')!;
  const built = normalizeBuild(part.build!(createBuildContext(part, r.params, services, new SimpleGeometryCache(), {})));
  const label = built.object.getObjectByName('can.label') as THREE.Mesh;
  label.geometry.computeBoundingBox();
  console.log('bbox', label.geometry.boundingBox, 'verts', label.geometry.attributes.position!.count, 'index', label.geometry.index?.count);
  const n = label.geometry.attributes.normal!;
  const p = label.geometry.attributes.position!;
  const uv = label.geometry.attributes.uv!;
  for (const i of [0, 5, 50]) console.log('p', p.getX(i), p.getY(i), p.getZ(i), 'n', n.getX(i), n.getY(i), n.getZ(i), 'uv', uv.getX(i), uv.getY(i));
  console.log('req', services.textures.requests.map((q) => `${q.key} ${q.width}x${q.height}`));
  const body = built.object.getObjectByName('can.body') as THREE.Mesh;
  body.geometry.computeBoundingBox();
  console.log('body', body.geometry.boundingBox);
});
