/**
 * Pièces du boîtier de dérivation d'exemple : hiérarchie, fiches, éclatement et retrait.
 *
 * Rappels du contrat (`objects/types.ts`) :
 * - `explode.direction` et `removal.axis` sont exprimés dans le repère du PARENT ;
 * - l'origine de l'objet retourné par `build` est le pivot (axe des vis) ;
 * - `removal.requires` liste les pièces à retirer AVANT (ids ou `#tag`) ; une pièce d'un
 *   sous-ensemble retirable exige en plus que ce sous-ensemble soit retiré (règle implicite).
 */
import type { PartDef } from '../types';
import {
  buildBase,
  buildBoard,
  buildBoardScrews,
  buildGasket,
  buildGrommets,
  buildLed,
  buildLid,
  buildLidScrews,
  buildResistor,
  buildTerminal,
  buildWires,
  type BoxParams,
} from './build';

/** Pièces présentes seulement avec la carte témoin (variante `indicator`). */
const withIndicator = (p: BoxParams): boolean => p.indicator;

export const PARTS: readonly PartDef<BoxParams>[] = [
  {
    id: 'base',
    name: 'Boîte (base)',
    material: 'exemple-boitier/abs.gray',
    build: buildBase,
    info: {
      role: 'Enveloppe étanche qui reçoit les raccordements ; protège contre les contacts directs et les projections d’eau.',
      material: 'ABS/PC ignifugé (UL94 V-0), gris clair RAL 7035',
      dimensions: '80 × 80 × 36 mm (extérieur), parois 2,2 mm',
      reference: 'Boîte étanche 80 × 80 IP55 (typique)',
      tip: 'Les entrées de câbles se font par les membranes : ne jamais agrandir un trou au cutter, l’indice IP serait perdu.',
      extra: [{ label: 'Indice de protection', value: 'IP55 (couvercle vissé, joint en place)' }],
    },
    explode: { direction: [0, 1, 0], distance: 0 },
    label: { priority: 2 },
  },
  {
    id: 'screws',
    name: 'Vis de couvercle',
    material: 'steel.zinc',
    quantity: 4,
    build: buildLidScrews,
    info: {
      role: 'Fixent le couvercle dans les fûts d’angle et compriment le joint.',
      material: 'Acier zingué blanc',
      dimensions: 'Ø 4 × 16 mm, tête bombée Ø 7,5 mm, empreinte cruciforme PH2',
      reference: 'Vis autotaraudeuse pour plastique Ø 4 × 16 (typique)',
      tip: 'Dans le plastique, un serrage excessif arrache le filet : s’arrêter dès le contact, puis un quart de tour.',
      extra: [{ label: 'Filet', value: 'Pas 0,7 mm (représentation simplifiée)' }],
    },
    explode: { direction: [0, 1, 0], distance: 0.06 },
    removal: {
      motion: 'unscrew',
      axis: [0, 1, 0],
      distance: 0.028,
      turns: 10,
      pitch: 0.0007,
      tool: 'screwdriver-phillips',
      stagger: 0.18,
      gesture: 'Dévisser les quatre vis d’angle (sens antihoraire).',
    },
    knolling: { layout: 'row' },
  },
  {
    id: 'lid',
    name: 'Couvercle',
    kind: 'assembly',
    material: 'exemple-boitier/abs.gray',
    build: buildLid,
    info: {
      role: 'Ferme la boîte ; sa lèvre centre le couvercle et son joint assure l’étanchéité.',
      material: 'ABS/PC, même teinte que la base ; étiquette papier imprimée',
      dimensions: '80 × 80 × 5,2 mm',
      tip: 'Serrer les vis en croix pour comprimer le joint uniformément.',
    },
    explode: { direction: [0, 1, 0], distance: 0.04 },
    removal: {
      requires: ['screws'],
      motion: 'translate',
      axis: [0, 1, 0],
      distance: 0.05,
      tool: 'hands',
      gesture: 'Soulever le couvercle bien à plat pour ne pas pincer le joint.',
    },
  },
  {
    id: 'lid.gasket',
    name: 'Joint de couvercle',
    parent: 'lid',
    material: 'rubber.black',
    build: buildGasket,
    info: {
      role: 'Assure l’étanchéité entre le couvercle et la tranche des parois.',
      material: 'EPDM cellulaire',
      dimensions: 'Section 2 × 1,2 mm, périmètre ≈ 300 mm',
      tip: 'Un joint écrasé ou durci ne reprend plus sa forme : le remplacer si la boîte est installée en extérieur.',
    },
    explode: { direction: [0, -1, 0], distance: 0.015 },
    removal: {
      motion: 'peel',
      axis: [0, -1, 0],
      distance: 0.02,
      tool: 'spudger',
      after: 'park',
      gesture: 'Décoller le joint de sa gorge avec un levier plastique.',
    },
  },
  {
    id: 'wires',
    name: 'Conducteurs de liaison',
    material: 'copper.bare',
    quantity: 2,
    enabled: withIndicator,
    build: buildWires,
    info: {
      role: 'Alimentent la carte témoin depuis le bornier.',
      material: 'Âme cuivre souple, isolant PVC, embouts étamés sertis',
      dimensions: '0,75 mm², longueur ≈ 40 mm',
      tip: 'Marron = phase, bleu = neutre : respecter le code couleur même en très basse tension facilite le dépannage.',
    },
    explode: { direction: [0, 1, 0], distance: 0.05, spread: { mode: 'linear', step: [0.006, 0, 0] } },
    removal: {
      requires: ['lid'],
      motion: 'spread',
      axis: [0, 1, 0],
      distance: 0.035,
      spread: { mode: 'linear', step: [0.004, 0, 0] },
      stagger: 0.25,
      tool: 'screwdriver-precision',
      gesture: 'Desserrer les bornes, écarter puis extraire les deux conducteurs.',
    },
    knolling: { layout: 'row' },
  },
  {
    id: 'terminal',
    name: 'Bornier 3 pôles',
    material: 'exemple-boitier/pa.terminal',
    build: buildTerminal,
    info: {
      role: 'Raccorde les conducteurs d’arrivée et de départ.',
      material: 'Corps polyamide PA66, cages en laiton, vis en acier zingué',
      dimensions: '23 × 13 × 14 mm, pas 7,5 mm',
      reference: 'Bornier à vis 3P 4 mm² (typique)',
      tip: 'Un conducteur souple doit recevoir un embout serti avant d’être serré sous une vis.',
    },
    explode: { direction: [-0.5, 1, -0.3], distance: 0.035 },
    removal: {
      requires: ['lid', 'wires'],
      motion: 'unclip',
      axis: [0, 1, 0],
      distance: 0.03,
      tool: 'screwdriver-flat',
      gesture: 'Écarter le clip avec un tournevis plat et basculer le bornier hors de ses glissières.',
    },
  },
  {
    id: 'board.screws',
    name: 'Vis de la carte',
    material: 'steel.zinc',
    quantity: 2,
    enabled: withIndicator,
    build: buildBoardScrews,
    info: {
      role: 'Maintiennent la carte sur ses plots moulés.',
      material: 'Acier zingué',
      dimensions: 'Ø 2,5 × 6 mm, tête bombée Ø 4,6 mm, empreinte PH1',
    },
    explode: { direction: [0, 1, 0], distance: 0.05 },
    removal: {
      requires: ['lid'],
      motion: 'unscrew',
      axis: [0, 1, 0],
      distance: 0.02,
      turns: 5,
      pitch: 0.00045,
      tool: 'screwdriver-precision',
      stagger: 0.3,
    },
    knolling: { layout: 'row' },
  },
  {
    id: 'board',
    name: 'Carte témoin',
    kind: 'assembly',
    material: 'fr4.core',
    enabled: withIndicator,
    build: buildBoard,
    info: {
      role: 'Allume un voyant quand la ligne est sous tension.',
      material: 'Stratifié FR-4 1,6 mm, cuivre 35 µm, vernis épargne vert',
      dimensions: '40 × 26 × 1,6 mm',
      tip: 'Pour une tension secteur, le témoin utiliserait un condensateur de chute ou une résistance de forte puissance : cette carte est prévue pour 12–24 V.',
    },
    explode: { direction: [0.3, 1, 0.4], distance: 0.035 },
    removal: {
      requires: ['board.screws', 'wires'],
      motion: 'lift',
      axis: [0, 1, 0],
      distance: 0.04,
      tool: 'hands',
      gesture: 'Soulever la carte par un bord pour la dégager des plots.',
    },
  },
  {
    id: 'board.led',
    name: 'LED témoin',
    parent: 'board',
    tags: ['soldered'],
    material: 'led.red',
    enabled: withIndicator,
    build: buildLed,
    info: {
      role: 'Signale la présence de tension.',
      material: 'Boîtier époxy diffusant rouge, pattes en acier étamé',
      dimensions: 'Ø 5 mm, entraxe 2,54 mm',
      reference: 'LED 5 mm rouge, 20 mA max',
      tip: 'La cathode est repérée par le méplat du boîtier et la patte la plus courte.',
    },
    explode: { direction: [0, 1, 0], distance: 0.018 },
    removal: {
      motion: 'desolder',
      axis: [0, 1, 0],
      distance: 0.02,
      tool: 'soldering-iron',
      destructive: false,
      gesture: 'Chauffer chaque soudure, aspirer l’étain, puis retirer la LED.',
    },
  },
  {
    id: 'board.resistor',
    name: 'Résistance de limitation',
    parent: 'board',
    tags: ['soldered'],
    material: 'ceramic.tan',
    enabled: withIndicator,
    build: buildResistor,
    info: {
      role: 'Limite le courant dans la LED.',
      material: 'Film carbone sur céramique, revêtement laqué',
      dimensions: 'Ø 2,3 × 6,3 mm, entraxe 10,16 mm',
      reference: '1 kΩ ¼ W 5 % (marron-noir-rouge-or)',
      tip: 'I = (U − U_LED) / R : sous 12 V, (12 − 2) / 1 000 ≈ 10 mA.',
    },
    explode: { direction: [0, 1, 0], distance: 0.014 },
    removal: {
      motion: 'desolder',
      axis: [0, 1, 0],
      distance: 0.018,
      tool: 'soldering-iron',
    },
  },
  {
    id: 'grommets',
    name: 'Membranes passe-câbles',
    material: 'exemple-boitier/tpe.gray',
    quantity: 2,
    build: buildGrommets,
    info: {
      role: 'Laissent passer les câbles tout en préservant l’étanchéité.',
      material: 'Élastomère thermoplastique (TPE)',
      dimensions: 'Ø 16 mm, pour câbles Ø 4 à 10 mm',
      tip: 'Percer la membrane au plus petit diamètre possible : l’élastomère doit serrer la gaine.',
    },
    explode: { direction: [-1, 0, 0], distance: 0.03 },
    removal: {
      requires: ['lid'],
      motion: 'pressOut',
      axis: [-1, 0, 0],
      distance: 0.025,
      tool: 'hands',
      stagger: 0.3,
      gesture: 'Pousser chaque membrane depuis l’intérieur de la boîte.',
    },
    knolling: { layout: 'row' },
  },
];
